In [6]:
# Implementetion multiple operations on a multi-dimensional array.
# Create an array with random integers between 1 and 20 with shape [M,N]
# The dimension N is called the sequence length.
# Add few zeros in this matrix randomly
# Define a matrix of shape [V,D] where V=30 and D=15
# The first operation will be to index the embedding matrix in order to get a matrix of shape [M,N,D] 
# where essentially for each token id in the matrix of integers 
# we will get the corresponding vector from the embedding matrix.
# Apply the following operations: 𝑋𝑎𝑣𝑔=𝐴𝑣𝑒𝑟𝑎𝑔𝑒(𝑋)
# On the axis of the sequence length without taking into account any zero vectors in the average. 
# You will have after this operation a matrix with shape [M,D].
# Then, define two weight matrices W and W1 of shapes [D,K] and [K,C] where K=5 and C=3 with seed=1
# and uniform distribution and perform the following operations on the second axis: 𝐿=𝑚𝑎𝑥(𝑋𝑎𝑣𝑔∗𝑊,0)∗𝑊1  𝑃=𝑒𝐿/∑𝐶−1𝑘=0*𝑒𝐿𝑘




from numpy.random import default_rng
import numpy as np

rng = default_rng(seed=10)
matrix = rng.integers(1, 20, (5, 10))

V, D = 20, 15  
embedding_matrix = rng.uniform(low=0.0, high=1.0, size=(V + 1, D))

X = embedding_matrix[matrix]

X_avg = np.mean(X, axis=1)


rng = default_rng(seed=1)

K, C = 5, 3

W = rng.uniform(low=-1.0, high=1.0, size=(D, K))

W1 = rng.uniform(low=-1.0, high=1.0, size=(K, C))


L = np.dot(X_avg, W)
L = np.maximum(L, 0)
L = np.dot(L, W1)



def softmax(x):
    e_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return e_x / e_x.sum(axis=1, keepdims=True)


P = softmax(L)

row_sums = np.sum(P, axis=1)

print("Row sums (sanity check):", row_sums)


print("Softmax Output P:")


print(P)

Row sums (sanity check): [1. 1. 1. 1. 1.]
Softmax Output P:
[[0.40125695 0.06769417 0.53104888]
 [0.42342034 0.06075429 0.51582538]
 [0.40527842 0.09092023 0.50380135]
 [0.31864523 0.09706355 0.58429122]
 [0.27196917 0.12691473 0.6011161 ]]
