In [3]:
# Create a matrix X of size m × m where approximately 80% of the values are
# zeros and the rest are random integers between 1 and 30
# Then factorize this matrix using ‘Singular Value Decomposition‘ 
# Then truncate the first k dimensions of the left singular matrix and multiply
# with the corresponding truncation of the diagonal matrix. E = U:,:k Σ a :k where a=0.5


import numpy as np

class MatrixOper:
    def __init__(self, size):
        self.size = size  # square matrix size m x m

    def generate_matrix(self):
        
        matrix = np.zeros((self.size, self.size), dtype=int) # matrix full of zero
        num_values = int(0.2 * self.size * self.size)
        indices = np.random.choice(self.size * self.size, num_values, replace=False) # replace zero values by non zero by 20%
        values = np.random.randint(1, 31, size=num_values) # generate random non zero
        np.put(matrix, indices, values) # put them in matrix
        return matrix

    def perform_svd_truncate(self, matrix, k, alpha=0.5):
    
        U, sigma, VT = np.linalg.svd(matrix, full_matrices=False) # singular value decomposition
        Sigma = np.diag(sigma[:k]**alpha)  # apply power to Sigma and truncate
        U_k = U[:, :k]  # truncate U
        E = np.dot(U_k, Sigma) # matrix multiplication
        return E

#Usage 
matrix_ops = MatrixOper(size=12)  # random size number
X = matrix_ops.generate_matrix()
E = matrix_ops.perform_svd_truncate(X, k=3)  # random k dimensions

print("Original Matrix X:", X)
print("Truncated Matrix E:", E)


Original Matrix X: [[ 0  2  0  0  0  0  0  3  0  0  9  0]
 [ 0  0  0  0  0  8  0  0 28  0  0  0]
 [16  0  0 26  0 19  0  0  0  0  0  0]
 [12  0  0  3  0  0 30  4  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0 26  0 13]
 [ 0  0  6  0  0  0  0 27  0  0  0  0]
 [10 22  0  0 29  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 26  2  0  0 26  7  0]
 [ 0  0  0  0  0  0  0  0  0  0 17  0]
 [ 0  0  0  0  7  0  0  0  0  0  0 20]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  7]]
Truncated Matrix E: [[-0.23341368  0.06856088  0.08621802]
 [-1.05868589 -0.75575032 -0.64748893]
 [-3.26148702 -0.08875361 -3.71156375]
 [-1.18719156  1.24363827 -3.08651451]
 [-2.89681017 -0.05718958  3.07481493]
 [-0.09985086  0.19357972 -0.55045605]
 [-1.7710881   5.48547711  0.84475671]
 [-4.69366334 -2.25880465  1.12504585]
 [-0.30483701 -0.21552136  0.13759302]
 [-0.63441285  1.07149494  1.11964273]
 [ 0.          0.          0.        ]
 [-0.16096775  0.1006621   0.33353309]]
